docs_dir: doc/book/ru
pages:
    - index.md
site_name: form-comparator
site_description: 'Модуль для сравнения форм'
repo_url: 'https://github.com/nnx-framework/form-comparator'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
